In [ ]:
#Kaggle House Pricing Advanced Regression Model

import torch
import pandas as pd
import sklearn 
import numpy as np
import matplotlib.pyplot as plt

train_set = pd.read_csv("/Users/xDAyN/Desktop/cs project/kaggle/House Prices/house-prices-advanced-regression-techniques/train.csv", usecols=["SalePrice", "MSSubClass", "MSZoning", "LotFrontage", "LotArea", "Street", "YearBuilt", "LotShape", "1stFlrSF", "2ndFlrSF"]).dropna()
test_set = pd.read_csv("/Users/xDAyN/Desktop/cs project/kaggle/House Prices/house-prices-advanced-regression-techniques/train.csv", usecols=[ "MSSubClass", "MSZoning", "LotFrontage", "LotArea", "Street", "YearBuilt", "LotShape", "1stFlrSF", "2ndFlrSF"]).dropna()

import datetime

train_set['Total Years'] = datetime.datetime.now().year - train_set["YearBuilt"]
train_set.drop("YearBuilt", axis=1,inplace=True)

#splitting features into categorical and continuos
cat_features = ["MSSubClass", "MSZoning", "Street", "LotShape"]
out_features = ["SalePrice"]

#convering unique values of MSSubClass into indexes using Laber Encoder to use Embedded Layer in the future
from sklearn.preprocessing import LabelEncoder #This encodes the target labels from 0 to n-1 unique values, and it defines the order for categorical features. For example, a category of cats and dogs will now become 0 and 1, allowing us to work with subsequent numbers instead of text. Even if the numbers werre categorised before, such as either 14.5 or 17.5, now will become 0 and 1, or (n-1) depending on number of unique features. This is why Scikit-Learn is important.
lbl_encoders = {}
for feature in cat_features:
  lbl_encoders[feature] = LabelEncoder()
  train_set[feature] = lbl_encoders[feature].fit_transform(train_set[feature])


#convert categorical features from numpy into torch tensors
cat_features = np.stack([train_set["MSSubClass"], train_set["MSZoning"], train_set["Street"], train_set["LotShape"]],1) #the data in these columns is now in one array. Now convert to tensors
cat_features = torch.tensor(cat_features, dtype=torch.int64)
print(cat_features)


cont_features = []
for i in train_set.columns:
  if i in ["MSSubClass", "MSZoning", "Street", "LotShape", "SalePrice"]:
    pass
  else:
    cont_features.append(i)

cont_features = np.stack([train_set[i].values for i in cont_features],1)
cont_features = torch.tensor(cont_features, dtype=torch.float)
print(cont_features)

y=torch.tensor(train_set["SalePrice"].values, dtype=torch.float).reshape(-1,1)
print(y)


#embedding layers for cat features



tensor([[5, 3, 1, 3],
        [0, 3, 1, 3],
        [5, 3, 1, 0],
        ...,
        [6, 3, 1, 3],
        [0, 3, 1, 3],
        [0, 3, 1, 3]])
tensor([[   65.,  8450.,   856.,   854.,    22.],
        [   80.,  9600.,  1262.,     0.,    49.],
        [   68., 11250.,   920.,   866.,    24.],
        ...,
        [   66.,  9042.,  1188.,  1152.,    84.],
        [   68.,  9717.,  1078.,     0.,    75.],
        [   75.,  9937.,  1256.,     0.,    60.]])
tensor([[208500.],
        [181500.],
        [223500.],
        ...,
        [266500.],
        [142125.],
        [147500.]])
